services:
  fe:
    image: apache/doris:fe-4.0.2
    hostname: fe
    networks:
      my-network:
        ipv4_address: 172.20.81.2
    ports:
      - "8030:8030"
      - "9030:9030"
    environment:
      - FE_SERVERS=fe1:172.20.81.2:9010
      - FE_ID=1
    volumes:
      - ./data/dockerData/doris/fe/doris-meta:/opt/apache-doris/fe/doris-meta
      - ./data/dockerData/doris/fe/log:/opt/apache-doris/fe/log

  be:
    image: apache/doris:be-4.0.2
    hostname: be
    networks:
      my-network:
        ipv4_address: 172.20.81.3
    ports:
      - "8040:8040"
    environment:
      - FE_SERVERS=fe1:172.20.81.2:9010
      - BE_ADDR=172.20.81.3:9050
    volumes:
      - ./data/dockerData/doris/be/storage:/opt/apache-doris/be/storage
      - ./data/dockerData/doris/be/log:/opt/apache-doris/be/log
    depends_on:
      - fe

networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.81.0/24
